### ISSUE TITLE
bmob建表

### ISSUE THREAD

**Issue by stevenwsg** [conghuahuadan/CNiaoShops#1]
可以详细一下bmob的建表吗？

**Comment by stevenwsg** [comment]
@conghuahuadan

**Comment by conghuahuadan** [comment]
你看下bmob的开发文档，很简单的，有个[快速入门](https://docs.bmob.cn/data/Android/a_faststart/doc/index.html)，照着它做就会了

**Comment by stevenwsg** [comment]
谢谢你
